# Data preprocessing

### 전처리 연습 (Tokenize, Cleansing & Normalization, Stemming & Lemmatization)

In [19]:
import pandas as pd

df = pd.read_csv('./data/raw_data/merged_data.csv')
df.head(5)

,date,occupation,channel,place,gender,ageRange,question_raw,answer_raw
0,20230116,ARD,MOCK,ONLINE,FEMALE,-34,면접자께서는 지금부터 삼 년 뒤까지 삼 년 내 주요 성장 계획이나 목표가 있으십니까...,네 저는 디자이너로서 삼 년 안에 저만의 브랜드를 만드는 게 목표입니다. 어 아직까...
1,20230116,ARD,MOCK,ONLINE,FEMALE,-34,업무를 하다가 만일 상사가 지원자님에게 어려운 지시를 준다면 어떻게 극복하시겠어요,네 디자인을 하다가 제가 이제 메인 디자이너 상사께 받은 여러 가지 지시 사항이 있...
2,20230116,ARD,MOCK,ONLINE,FEMALE,-34,그 이전 직장에서 그 퇴사를 하셨는데요 뭐 퇴사하신 것을 혹시라도 후회하신 적은 없...,네 저는 전에 직장에서 일할 수 있었다는 걸 굉장히 감사하게 생각을 하고요. 퇴사한...
3,20230116,ARD,MOCK,ONLINE,FEMALE,-34,주로 영감은 어디에서 찾으시나요,네 디자인 일을 할 때는 아무래도 영감 그리고 아이디어를 얻는 일이 참 중요합니다....
4,20230116,ARD,MOCK,ONLINE,FEMALE,-34,일을 하다 보면 상사와 트러블이 생길 수가 있는데요 어떻게 하면 좋을까요 또 상사가...,네 일단 업무를 하다보면 어 상사와 트러블이 발생할 수도 있을 것 같습니다. 그리고...

##### Tokenize

In [20]:
import kss

text = df['answer_raw'][0]

kss.split_sentences(text)

['네 저는 디자이너로서 삼 년 안에 저만의 브랜드를 만드는 게 목표입니다.',
 '어 아직까지 저는 디자이너로서 서포트한 업무를 많이 진행을 했습니다.',
 '그래서 주요 디자이너의 업무를 제가 도와드리고 그리고 그거 관련해서 어떤 파트에 제가 일을 하는 경우가 많았는데요.',
 '어 저는 앞으로 삼 년 안에 제가 주도하에 메인 디자이너로서 성공하는 게 저의 목표입니다.',
 '어 아무래도 저만의 색깔 저만의 아이디어를 통해서 디자이너를 구축을 하고 싶고요.',
 '그리고 또 제가 메인으로서 참여를 해서 어 브랜드를 좀 만드는 게 저의 목표입니다.',
 '그러기 위해서 삼 년 동안 또 많은 연습과 준비를 해야 할 텐데요.',
 '일단은 회사 입사해서 삼 년 동안 경력을 쌓으면서 어 계속해서 제 실력을 다져 나가고자 하는 목표가 있고요.',
 '그리고 그 안에서는 트렌드를 파악하고 또 저만의 색깔을 구축함으로써 뭔가 그거를 확실하게 다질 수 있는 입지를 다질 수 있는 그런 계획을 가지고 있습니다.',
 '앞으로 삼 년 동안 제가 최선을 다해서 일을 하고 또 디자인을 한다고 하면 저는 충분히 가능하다고 보고요.',
 '저의 성장 가능성을 믿고 그리고 입사를 할 수 있었으면 좋겠습니다.']

In [21]:
from konlpy.tag import Okt

okt = Okt()
print(okt.morphs(text))                     # 형태소 분석
print(okt.pos(text))                        # 품사 태깅
print(okt.nouns(text))                      # 명사 추출

['네', '저', '는', '디자이너', '로서', '삼', '년', '안', '에', '저', '만의', '브랜드', '를', '만드는', '게', '목표', '입니다', '.', '어', '아직', '까지', '저', '는', '디자이너', '로서', '서', '포트', '한', '업무', '를', '많이', '진행', '을', '했습니다', '.', '그래서', '주요', '디자이너', '의', '업무', '를', '제', '가', '도', '와', '드리고', '그리고', '그거', '관련', '해서', '어떤', '파트', '에', '제', '가', '일', '을', '하는', '경우', '가', '많았는데요', '.', '어', '저', '는', '앞', '으로', '삼', '년', '안', '에', '제', '가', '주도하에', '메인', '디자이너', '로서', '성공하는', '게', '저', '의', '목표', '입니다', '.', '어', '아무래도', '저', '만의', '색깔', '저', '만의', '아이디어', '를', '통해', '서', '디자이너', '를', '구축', '을', '하고', '싶고요', '.', '그리고', '또', '제', '가', '메인', '으로서', '참여', '를', '해서', '어', '브랜드', '를', '좀', '만드는', '게', '저', '의', '목표', '입니다', '.', '그러기', '위해', '서', '삼', '년', '동안', '또', '많은', '연습', '과', '준비', '를', '해야', '할', '텐데요', '.', '일단', '은', '회사', '입사', '해서', '삼', '년', '동안', '경력', '을', '쌓으면서', '어', '계속', '해서', '제', '실력', '을', '다져', '나가고자', '하는', '목표', '가', '있고요', '.', '그리고', '그', '안', '에서는', '트렌드', '를', '파악', '하고', '또', '저', '만의', '색깔', '을', '구축함', '으로써', '뭔가', '그거', '를', '확실하게', '다질', '수', '있는', '입지', '를', '다질', '수', '있는', '그런', '계획', '을', '가지', '고', '있습니다', '.', '앞', '으로', '삼', '년', '동안', '제', '가', '최선', '을', '다해', '서', '일', '을', '하고', '또', '디자인', '을', '한다고', '하면', '저', '는', '충분히', '가능하다고', '보고', '요', '.', '저', '의', '성장', '가능성', '을', '믿고', '그리고', '입사', '를', '할', '수', '있었으면', '좋겠습니다', '.']
[('네', 'Noun'), ('저', 'Noun'), ('는', 'Josa'), ('디자이너', 'Noun'), ('로서', 'Noun'), ('삼', 'Noun'), ('년', 'Noun'), ('안', 'Noun'), ('에', 'Josa'), ('저', 'Noun'), ('만의', 'Josa'), ('브랜드', 'Noun'), ('를', 'Josa'), ('만드는', 'Verb'), ('게', 'Noun'), ('목표', 'Noun'), ('입니다', 'Adjective'), ('.', 'Punctuation'), ('어', 'Eomi'), ('아직', 'Adverb'), ('까지', 'Josa'), ('저', 'Noun'), ('는', 'Josa'), ('디자이너', 'Noun'), ('로서', 'Noun'), ('서', 'Modifier'), ('포트', 'Noun'), ('한', 'Josa'), ('업무', 'Noun'), ('를', 'Josa'), ('많이', 'Adverb'), ('진행', 'Noun'), ('을', 'Josa'), ('했습니다', 'Verb'), ('.', 'Punctuation'), ('그래서', 'Adverb'), ('주요', 'Noun'), ('디자이너', 'Noun'), ('의', 'Josa'), ('업무', 'Noun'), ('를', 'Josa'), ('제', 'Noun'), ('가', 'Josa'), ('도', 'Noun'), ('와', 'Josa'), ('드리고', 'Verb'), ('그리고', 'Conjunction'), ('그거', 'Noun'), ('관련', 'Noun'), ('해서', 'Verb'), ('어떤', 'Adjective'), ('파트', 'Noun'), ('에', 'Josa'), ('제', 'Noun'), ('가', 'Josa'), ('일', 'Noun'), ('을', 'Josa'), ('하는', 'Verb'), ('경우', 'Noun'), ('가', 'Josa'), ('많았는데요', 'Adjective'), ('.', 'Punctuation'), ('어', 'Eomi'), ('저', 'Noun'), ('는', 'Josa'), ('앞', 'Noun'), ('으로', 'Josa'), ('삼', 'Noun'), ('년', 'Noun'), ('안', 'Noun'), ('에', 'Josa'), ('제', 'Noun'), ('가', 'Josa'), ('주도하에', 'Adjective'), ('메인', 'Noun'), ('디자이너', 'Noun'), ('로서', 'Noun'), ('성공하는', 'Adjective'), ('게', 'Noun'), ('저', 'Noun'), ('의', 'Josa'), ('목표', 'Noun'), ('입니다', 'Adjective'), ('.', 'Punctuation'), ('어', 'Eomi'), ('아무래도', 'Adverb'), ('저', 'Noun'), ('만의', 'Josa'), ('색깔', 'Noun'), ('저', 'Noun'), ('만의', 'Josa'), ('아이디어', 'Noun'), ('를', 'Josa'), ('통해', 'Noun'), ('서', 'Josa'), ('디자이너', 'Noun'), ('를', 'Josa'), ('구축', 'Noun'), ('을', 'Josa'), ('하고', 'Verb'), ('싶고요', 'Verb'), ('.', 'Punctuation'), ('그리고', 'Conjunction'), ('또', 'Noun'), ('제', 'Noun'), ('가', 'Josa'), ('메인', 'Noun'), ('으로서', 'Josa'), ('참여', 'Noun'), ('를', 'Josa'), ('해서', 'Verb'), ('어', 'Eomi'), ('브랜드', 'Noun'), ('를', 'Josa'), ('좀', 'Noun'), ('만드는', 'Verb'), ('게', 'Noun'), ('저', 'Noun'), ('의', 'Josa'), ('목표', 'Noun'), ('입니다', 'Adjective'), ('.', 'Punctuation'), ('그러기', 'Adjective'), ('위해', 'Noun'), ('서', 'Josa'), ('삼', 'Noun'), ('년', 'Noun'), ('동안', 'Noun'), ('또', 'Noun'), ('많은', 'Adjective'), ('연습', 'Noun'), ('과', 'Josa'), ('준비', 'Noun'), ('를', 'Josa'), ('해야', 'Verb'), ('할', 'Verb'), ('텐데요', 'Eomi'), ('.', 'Punctuation'), ('일단', 'Noun'), ('은', 'Josa'), ('회사', 'Noun'), ('입사', 'Noun'), ('해서', 'Verb'), ('삼', 'Noun'), ('년', 'Noun'), ('동안', 'Noun'), ('경력', 'Noun'), ('을', 'Josa'), ('쌓으면서', 'Verb'), ('어', 'Eomi'), ('계속', 'Noun'), ('해서', 'Verb'), ('제', 'Noun'), ('실력', 'Noun'), ('을', 'Josa'), ('다져', 'Verb'), ('나가고자', 'Verb'), ('하는', 'Verb'), ('목표', 'Noun'), ('가', 'Josa'), ('있고요', 'Adjective'), ('.', 'Punctuation'), ('그리고', 'Conjunction'), ('그', 'Noun'), ('안', 'Noun'), ('에서는', 'Josa'), ('트렌드', 'Noun'), ('를', 'Josa'), ('파악', 'Noun'), ('하고', 'Josa'), ('또', 'Noun'), ('저', 'Noun'), ('만의', 'Josa'), ('색깔', 'Noun'), ('을', 'Josa'), ('구축함', 'Noun'), ('으로써', 'Josa'), ('뭔가', 'Noun'), ('그거', 'Noun'), ('를', 'Josa'), ('확실하게', 'Adjective'), ('다질', 'Verb'), ('수', 'Noun'), ('있는', 'Adjective'), ('입지', 'Noun'), ('를', 'Josa'), ('다질', 'Verb'), ('수', 'Noun'), ('있는', 'Adjective'), ('그런', 'Adjective'), ('계획', 'Noun'), ('을', 'Josa'), ('가지', 'Noun'), ('고', 'Josa'), ('있습니다', 'Adjective'), ('.', 'Punctuation'), ('앞', 'Noun'), ('으로', 'Josa'), ('삼', 'Noun'), ('년', 'Noun'), ('동안', 'Noun'), ('제', 'Noun'), ('가', 'Josa'), ('최선', 'Noun'), ('을', 'Josa'), ('다해', 'Noun'), ('서', 'Josa'), ('일', 'Noun'), ('을', 'Josa'), ('하고', 'Verb'), ('또', 'Noun'), ('디자인', 'Noun'), ('을', 'Josa'), ('한다고', 'Verb'), ('하면', 'Verb'), ('저', 'Noun'), ('는', 'Josa'), ('충분히', 'Adjective'), ('가능하다고', 'Adjective'), ('보고', 'Noun'), ('요', 'Josa'), ('.', 'Punctuation'), ('저', 'Noun'), ('의', 'Josa'), ('성장', 'Noun'), ('가능성', 'Noun'), ('을', 'Josa'), ('믿고', 'Verb'), ('그리고', 'Conjunction'), ('입사', 'Noun'), ('를', 'Josa'), ('할', 'Verb'), ('수', 'Noun'), ('있었으면', 'Adjective'), ('좋겠습니다', 'Adjective'), ('.', 'Punctuation')]
['네', '저', '디자이너', '로서', '삼', '년', '안', '저', '브랜드', '게', '목표', '저', '디자이너', '로서', '포트', '업무', '진행', '주요', '디자이너', '업무', '제', '도', '그거', '관련', '파트', '제', '일', '경우', '저', '앞', '삼', '년', '안', '제', '메인', '디자이너', '로서', '게', '저', '목표', '저', '색깔', '저', '아이디어', '통해', '디자이너', '구축', '또', '제', '메인', '참여', '브랜드', '좀', '게', '저', '목표', '위해', '삼', '년', '동안', '또', '연습', '준비', '일단', '회사', '입사', '삼', '년', '동안', '경력', '계속', '제', '실력', '목표', '그', '안', '트렌드', '파악', '또', '저', '색깔', '구축함', '뭔가', '그거', '수', '입지', '수', '계획', '가지', '앞', '삼', '년', '동안', '제', '최선', '다해', '일', '또', '디자인', '저', '보고', '저', '성장', '가능성', '입사', '수']

##### Cleansing & Normalization

In [22]:
# 한국어이므로 짧은 단어 삭제 시 의미 보존 어려움
# 빈도 수도 마찬가지

In [23]:
from nltk.corpus import stopwords

tokens = okt.morphs(text)
ko_stopwords = set('그 은 관련 많은 네 저 삼 년 안 에 만의 게 입니다 뭐 주로 어 까지 는 로서 가지 한다고 하면 뭔가 무언가 있고요 쌓으면서 아무래도 경우 아직 한 를 많이 을 했습니다 많았는데요 앞 그래서 의 를 제 가 도 와 드리고 그리고 그거 해서 어떤 을 으로 로써 만의 통해 서 하고 싶고요 싶어요 싶다 또 또한 좀 그러기 위해 동안 일 이 삼 사 오 육 칠 팔 구 십 하나 둘 셋 넷 다섯 여섯 일곱 여덟 아홉 열 해야 과 와 텐데요 텐데 일단 계속 나가고자 하고자 하는 했던 했나 에서는 으로써 으로서 수 있는 그런 고 있습니다 최선 다해 보고 요 할 수 있었으면 좋겠습니다'.split())
print(len(ko_stopwords))

cleand_tokens = [token for token in tokens if token not in ko_stopwords]
cleand_tokens

106

['디자이너',
 '브랜드',
 '만드는',
 '목표',
 '.',
 '디자이너',
 '포트',
 '업무',
 '진행',
 '.',
 '주요',
 '디자이너',
 '업무',
 '파트',
 '.',
 '주도하에',
 '메인',
 '디자이너',
 '성공하는',
 '목표',
 '.',
 '색깔',
 '아이디어',
 '디자이너',
 '구축',
 '.',
 '메인',
 '참여',
 '브랜드',
 '만드는',
 '목표',
 '.',
 '연습',
 '준비',
 '.',
 '회사',
 '입사',
 '경력',
 '실력',
 '다져',
 '목표',
 '.',
 '트렌드',
 '파악',
 '색깔',
 '구축함',
 '확실하게',
 '다질',
 '입지',
 '다질',
 '계획',
 '.',
 '디자인',
 '충분히',
 '가능하다고',
 '.',
 '성장',
 '가능성',
 '믿고',
 '입사',
 '.']

In [24]:
def save_ko_stopwords(filepath):
    with open(filepath, 'w', encoding='UTF-8') as f:
        for word in ko_stopwords:
            f.write(word + '\n')

save_stopwords = save_ko_stopwords('./ko_stopwords.txt')
save_stopwords

In [25]:
def load_ko_stopwords(filepath):
    with open(filepath, 'r', encoding='UTF-8') as f:
        return [line.strip() for line in f]
    
ko_stopwords = load_ko_stopwords('./ko_stopwords.txt')
cleand_tokens = [token for token in tokens if token not in ko_stopwords]
cleand_tokens

['디자이너',
 '브랜드',
 '만드는',
 '목표',
 '.',
 '디자이너',
 '포트',
 '업무',
 '진행',
 '.',
 '주요',
 '디자이너',
 '업무',
 '파트',
 '.',
 '주도하에',
 '메인',
 '디자이너',
 '성공하는',
 '목표',
 '.',
 '색깔',
 '아이디어',
 '디자이너',
 '구축',
 '.',
 '메인',
 '참여',
 '브랜드',
 '만드는',
 '목표',
 '.',
 '연습',
 '준비',
 '.',
 '회사',
 '입사',
 '경력',
 '실력',
 '다져',
 '목표',
 '.',
 '트렌드',
 '파악',
 '색깔',
 '구축함',
 '확실하게',
 '다질',
 '입지',
 '다질',
 '계획',
 '.',
 '디자인',
 '충분히',
 '가능하다고',
 '.',
 '성장',
 '가능성',
 '믿고',
 '입사',
 '.']

##### Stemming & Lemmatization

In [30]:
print(okt.morphs(text, stem= True))         # stem 어간 추출
print(okt.phrases(text))                    # 어절 추출

print(okt.pos(text, norm=True, stem=True))

['네', '저', '는', '디자이너', '로서', '삼', '년', '안', '에', '저', '만의', '브랜드', '를', '만들다', '게', '목표', '이다', '.', '어', '아직', '까지', '저', '는', '디자이너', '로서', '서', '포트', '한', '업무', '를', '많이', '진행', '을', '하다', '.', '그래서', '주요', '디자이너', '의', '업무', '를', '제', '가', '도', '와', '드리다', '그리고', '그거', '관련', '하다', '어떻다', '파트', '에', '제', '가', '일', '을', '하다', '경우', '가', '많다', '.', '어', '저', '는', '앞', '으로', '삼', '년', '안', '에', '제', '가', '주도하다', '메인', '디자이너', '로서', '성공하다', '게', '저', '의', '목표', '이다', '.', '어', '아무래도', '저', '만의', '색깔', '저', '만의', '아이디어', '를', '통해', '서', '디자이너', '를', '구축', '을', '하다', '싶다', '.', '그리고', '또', '제', '가', '메인', '으로서', '참여', '를', '하다', '어', '브랜드', '를', '좀', '만들다', '게', '저', '의', '목표', '이다', '.', '그렇다', '위해', '서', '삼', '년', '동안', '또', '많다', '연습', '과', '준비', '를', '하다', '하다', '텐데요', '.', '일단', '은', '회사', '입사', '하다', '삼', '년', '동안', '경력', '을', '쌓다', '어', '계속', '하다', '제', '실력', '을', '다지다', '나가다', '하다', '목표', '가', '있다', '.', '그리고', '그', '안', '에서는', '트렌드', '를', '파악', '하고', '또', '저', '만의', '색깔', '을', '구축함', '으로써', '뭔가', '그거', '를', '확실하다', '다지다', '수', '있다', '입지', '를', '다지다', '수', '있다', '그렇다', '계획', '을', '가지', '고', '있다', '.', '앞', '으로', '삼', '년', '동안', '제', '가', '최선', '을', '다해', '서', '일', '을', '하다', '또', '디자인', '을', '하다', '하다', '저', '는', '충분하다', '가능하다', '보고', '요', '.', '저', '의', '성장', '가능성', '을', '믿다', '그리고', '입사', '를', '하다', '수', '있다', '좋다', '.']
['디자이너로서', '디자이너로서 삼', '디자이너로서 삼 년', '디자이너로서 삼 년 안', '브랜드', '게 목표', '디자이너로서 서포트', '업무', '진행', '주요', '주요 디자이너', '주요 디자이너의 업무', '그거', '그거 관련', '어떤 파트', '경우', '메인', '메인 디자이너로서', '메인 디자이너로서 성공하는 게', '메인 디자이너로서 성공하는 게 저', '메인 디자이너로서 성공하는 게 저의 목표', '색깔', '색깔 저', '아이디어', '통해', '디자이너', '구축', '참여', '좀 만드는 게', '좀 만드는 게 저', '좀 만드는 게 저의 목표', '위해', '삼 년 동안', '삼 년 동안 또', '삼 년 동안 또 많은 연습', '삼 년 동안 또 많은 연습과 준비', '일단', '회사', '회사 입사', '삼 년 동안 경력', '계속', '제 실력', '목표', '트렌드', '파악', '구축함', '뭔가', '뭔가 그거', '수 있는 입지', '수 있는 그런 계획', '가지', '삼 년 동안 제', '최선', '다해', '또 디자인', '보고', '저의 성장', '저의 성장 가능성', '입사', '로서', '서포트', '관련', '파트', '동안', '연습', '준비', '경력', '실력', '입지', '계획', '디자인', '성장', '가능성']
[('네', 'Noun'), ('저', 'Noun'), ('는', 'Josa'), ('디자이너', 'Noun'), ('로서', 'Noun'), ('삼', 'Noun'), ('년', 'Noun'), ('안', 'Noun'), ('에', 'Josa'), ('저', 'Noun'), ('만의', 'Josa'), ('브랜드', 'Noun'), ('를', 'Josa'), ('만들다', 'Verb'), ('게', 'Noun'), ('목표', 'Noun'), ('이다', 'Adjective'), ('.', 'Punctuation'), ('어', 'Eomi'), ('아직', 'Adverb'), ('까지', 'Josa'), ('저', 'Noun'), ('는', 'Josa'), ('디자이너', 'Noun'), ('로서', 'Noun'), ('서', 'Modifier'), ('포트', 'Noun'), ('한', 'Josa'), ('업무', 'Noun'), ('를', 'Josa'), ('많이', 'Adverb'), ('진행', 'Noun'), ('을', 'Josa'), ('하다', 'Verb'), ('.', 'Punctuation'), ('그래서', 'Adverb'), ('주요', 'Noun'), ('디자이너', 'Noun'), ('의', 'Josa'), ('업무', 'Noun'), ('를', 'Josa'), ('제', 'Noun'), ('가', 'Josa'), ('도', 'Noun'), ('와', 'Josa'), ('드리다', 'Verb'), ('그리고', 'Conjunction'), ('그거', 'Noun'), ('관련', 'Noun'), ('하다', 'Verb'), ('어떻다', 'Adjective'), ('파트', 'Noun'), ('에', 'Josa'), ('제', 'Noun'), ('가', 'Josa'), ('일', 'Noun'), ('을', 'Josa'), ('하다', 'Verb'), ('경우', 'Noun'), ('가', 'Josa'), ('많다', 'Adjective'), ('.', 'Punctuation'), ('어', 'Eomi'), ('저', 'Noun'), ('는', 'Josa'), ('앞', 'Noun'), ('으로', 'Josa'), ('삼', 'Noun'), ('년', 'Noun'), ('안', 'Noun'), ('에', 'Josa'), ('제', 'Noun'), ('가', 'Josa'), ('주도하다', 'Adjective'), ('메인', 'Noun'), ('디자이너', 'Noun'), ('로서', 'Noun'), ('성공하다', 'Adjective'), ('게', 'Noun'), ('저', 'Noun'), ('의', 'Josa'), ('목표', 'Noun'), ('이다', 'Adjective'), ('.', 'Punctuation'), ('어', 'Eomi'), ('아무래도', 'Adverb'), ('저', 'Noun'), ('만의', 'Josa'), ('색깔', 'Noun'), ('저', 'Noun'), ('만의', 'Josa'), ('아이디어', 'Noun'), ('를', 'Josa'), ('통해', 'Noun'), ('서', 'Josa'), ('디자이너', 'Noun'), ('를', 'Josa'), ('구축', 'Noun'), ('을', 'Josa'), ('하다', 'Verb'), ('싶다', 'Verb'), ('.', 'Punctuation'), ('그리고', 'Conjunction'), ('또', 'Noun'), ('제', 'Noun'), ('가', 'Josa'), ('메인', 'Noun'), ('으로서', 'Josa'), ('참여', 'Noun'), ('를', 'Josa'), ('하다', 'Verb'), ('어', 'Eomi'), ('브랜드', 'Noun'), ('를', 'Josa'), ('좀', 'Noun'), ('만들다', 'Verb'), ('게', 'Noun'), ('저', 'Noun'), ('의', 'Josa'), ('목표', 'Noun'), ('이다', 'Adjective'), ('.', 'Punctuation'), ('그렇다', 'Adjective'), ('위해', 'Noun'), ('서', 'Josa'), ('삼', 'Noun'), ('년', 'Noun'), ('동안', 'Noun'), ('또', 'Noun'), ('많다', 'Adjective'), ('연습', 'Noun'), ('과', 'Josa'), ('준비', 'Noun'), ('를', 'Josa'), ('하다', 'Verb'), ('하다', 'Verb'), ('텐데요', 'Eomi'), ('.', 'Punctuation'), ('일단', 'Noun'), ('은', 'Josa'), ('회사', 'Noun'), ('입사', 'Noun'), ('하다', 'Verb'), ('삼', 'Noun'), ('년', 'Noun'), ('동안', 'Noun'), ('경력', 'Noun'), ('을', 'Josa'), ('쌓다', 'Verb'), ('어', 'Eomi'), ('계속', 'Noun'), ('하다', 'Verb'), ('제', 'Noun'), ('실력', 'Noun'), ('을', 'Josa'), ('다지다', 'Verb'), ('나가다', 'Verb'), ('하다', 'Verb'), ('목표', 'Noun'), ('가', 'Josa'), ('있다', 'Adjective'), ('.', 'Punctuation'), ('그리고', 'Conjunction'), ('그', 'Noun'), ('안', 'Noun'), ('에서는', 'Josa'), ('트렌드', 'Noun'), ('를', 'Josa'), ('파악', 'Noun'), ('하고', 'Josa'), ('또', 'Noun'), ('저', 'Noun'), ('만의', 'Josa'), ('색깔', 'Noun'), ('을', 'Josa'), ('구축함', 'Noun'), ('으로써', 'Josa'), ('뭔가', 'Noun'), ('그거', 'Noun'), ('를', 'Josa'), ('확실하다', 'Adjective'), ('다지다', 'Verb'), ('수', 'Noun'), ('있다', 'Adjective'), ('입지', 'Noun'), ('를', 'Josa'), ('다지다', 'Verb'), ('수', 'Noun'), ('있다', 'Adjective'), ('그렇다', 'Adjective'), ('계획', 'Noun'), ('을', 'Josa'), ('가지', 'Noun'), ('고', 'Josa'), ('있다', 'Adjective'), ('.', 'Punctuation'), ('앞', 'Noun'), ('으로', 'Josa'), ('삼', 'Noun'), ('년', 'Noun'), ('동안', 'Noun'), ('제', 'Noun'), ('가', 'Josa'), ('최선', 'Noun'), ('을', 'Josa'), ('다해', 'Noun'), ('서', 'Josa'), ('일', 'Noun'), ('을', 'Josa'), ('하다', 'Verb'), ('또', 'Noun'), ('디자인', 'Noun'), ('을', 'Josa'), ('하다', 'Verb'), ('하다', 'Verb'), ('저', 'Noun'), ('는', 'Josa'), ('충분하다', 'Adjective'), ('가능하다', 'Adjective'), ('보고', 'Noun'), ('요', 'Josa'), ('.', 'Punctuation'), ('저', 'Noun'), ('의', 'Josa'), ('성장', 'Noun'), ('가능성', 'Noun'), ('을', 'Josa'), ('믿다', 'Verb'), ('그리고', 'Conjunction'), ('입사', 'Noun'), ('를', 'Josa'), ('하다', 'Verb'), ('수', 'Noun'), ('있다', 'Adjective'), ('좋다', 'Adjective'), ('.', 'Punctuation')]

### BoW

### Word Embedding
- 참고용 메모: 불용어 더 넣어야 함 데이터가 덜 빠져서 학습이 덜 됨
    - 면접이라 답변이 긍정적 단어만 있을 것 같아서 고민 중
    - QnA를 합쳐서 관리해야 하는지도 의문

In [ ]:
import re

# 데이터 로드
df = pd.read_csv('./data/raw_data/merged_data.csv')

# 결측치 확인
df.isnull().sum()

date            0
occupation      0
channel         0
place           0
gender          0
ageRange        0
question_raw    0
answer_raw      0
dtype: int64

In [33]:
# 한글 아닌 데이터 제거
df['question_raw'] = df['question_raw'].replace(r'[^0-9가-힣ㄱ-ㅎㅏ-ㅣ\s]', '', regex=True)
df['answer_raw'] = df['answer_raw'].replace(r'[^0-9가-힣ㄱ-ㅎㅏ-ㅣ\s]', '', regex=True)

In [ ]:
from tqdm import tqdm
# def load_ko_stopwords(filepath):
#     with open(filepath, 'r', encoding='UTF-8') as f:
#         return [line.strip() for line in f]

def preprocess(sentences, ko_stopwords):
    result = []
    for sentence in tqdm(sentences):
        tokens = okt.morphs(sentence, stem=True)
        tokens = [token for token in tokens if token not in ko_stopwords]
        result.append(tokens)
    return result

ko_stopwords = load_ko_stopwords('./ko_stopwords.txt')
preprocessed_q_data = preprocess(df['question_raw'], ko_stopwords)
preprocessed_a_data = preprocess(df['answer_raw'], ko_stopwords)

100%|██████████| 76106/76106 [03:08<00:00, 403.43it/s]
100%|██████████| 76106/76106 [26:55<00:00, 47.11it/s]

In [ ]:
preprocessed_q_data

# 불용어 txt 수정 필요

[['면접',
  '자',
  '께서는',
  '지금',
  '부터',
  '뒤',
  '내',
  '주요',
  '성장',
  '계획',
  '이나',
  '목표',
  '있다',
  '있다',
  '무엇',
  '인지',
  '설명',
  '부탁드리다'],
 ['업무',
  '하다',
  '만일',
  '상사',
  '지',
  '원자',
  '님',
  '에게',
  '어렵다',
  '지시',
  '주다',
  '어떻다',
  '극복',
  '하다'],
 ['이전',
  '직장',
  '에서',
  '퇴사',
  '하다',
  '퇴사',
  '하다',
  '것',
  '혹시',
  '라도',
  '후회',
  '하다',
  '적다',
  '없다',
  '신지',
  '만약',
  '있다',
  '왜',
  '인지도',
  '이유',
  '함께',
  '말씀',
  '부탁',
  '드리다'],
 ['영감', '어디', '에서', '찾다'],
 ['하다',
  '보다',
  '상사',
  '트러블',
  '생기다',
  '수가',
  '있다',
  '어떻다',
  '하다',
  '좋다',
  '상사',
  '혼',
  '내면',
  '기분',
  '나쁘다',
  '않다'],
 ['지',
  '원자',
  '님',
  '께서',
  '생각',
  '하다',
  '때',
  '본인',
  '남',
  '자다',
  '이끌다',
  '리더',
  '형',
  '이다',
  '아니다',
  '남',
  '에게',
  '자다',
  '따르다',
  '팔로워',
  '형',
  '이다',
  '본인',
  '어떻다',
  '유형',
  '실지',
  '혹은',
  '왜',
  '유형',
  '일지',
  '이유',
  '함께',
  '설명',
  '하다',
  '줄다'],
 ['여기',
  '지금',
  '가상',
  '현실',
  '속이다',
  '게임',
  '속이다',
  '지',
  '원자',
  '님',
  '게임',
  '어떻다',
  '캐릭터',
  '어떻다',
  '역할',
  '맡다',
  '수행',
  '하다'],
 ['최근', '가장', '기억', '남다', '디자인', '사례', '있다', '거기', '대해', '말씀', '부탁드리다'],
 ['하다',
  '되다',
  '자료',
  '문서',
  '화하다',
  '일이',
  '많다',
  '지',
  '원자',
  '님',
  '께서는',
  '문서',
  '화',
  '작업',
  '왜',
  '필요하다',
  '생각',
  '하다',
  '들다'],
 ['본인',
  '직접',
  '해외',
  '출장',
  '장소',
  '고르다',
  '있다',
  '하다',
  '번',
  '가다',
  '해보다',
  '나라',
  '있다'],
 ['디자인',
  '전공자',
  '비',
  '전공자',
  '협업',
  '하다',
  '때',
  '가장',
  '어렵다',
  '점',
  '무엇',
  '이고',
  '어렵다',
  '점',
  '극복',
  '하다',
  '적용',
  '하다',
  '방법',
  '무엇',
  '인지',
  '말씀',
  '하다',
  '주다'],
 ['하다',
  '보다',
  '보통',
  '여러',
  '사람',
  '들',
  '함께',
  '하다',
  '되다',
  '여러',
  '사람',
  '들',
  '함께',
  '하다',
  '보다',
  '구성원',
  '들',
  '갈등',
  '생기',
  '기도',
  '하다',
  '이렇다',
  '때',
  '보통',
  '지',
  '원자',
  '님',
  '께서는',
  '어떻다',
  '해결',
  '하다',
  '편',
  '이다'],
 ['입사',
  '후',
  '만약',
  '상사',
  '업무',
  '무관',
  '시키다',
  '하다',
  '자다',
  '수행',
  '하다',
  '자신',
  '있다',
  '아니다',
  '수행',
  '하다',
  '않다',
  '건지다',
  '궁금하다',
  '답변',
  '하다',
  '주',
  '시기',
  '바라다'],
 ['지',
  '원자',
  '님',
  '주변',
  '친구',
  '분들',
  '중',
  '에서',
  '딱',
  '하다',
  '명',
  '골',
  '라서',
  '지금',
  '칭찬',
  '해주다',
  '최대한',
  '묘사',
  '구체',
  '적',
  '이고',
  '칭찬',
  '이유',
  '자세하다',
  '좋다'],
 ['지',
  '원자',
  '님',
  '께서',
  '본인',
  '있다',
  '위치',
  '보다',
  '어렵다',
  '목표',
  '달성',
  '하다',
  '경험',
  '있다',
  '어떠하다',
  '것',
  '있다',
  '설명',
  '하다',
  '주',
  '시기',
  '바라다'],
 ['지',
  '원자',
  '님',
  '께서',
  '생각',
  '하다',
  '하다',
  '가장',
  '어리다',
  '것',
  '예상',
  '되다',
  '것',
  '무엇',
  '있다',
  '가요',
  '상황',
  '에서',
  '어떻다',
  '대처',
  '하다',
  '생각',
  '이신',
  '지도',
  '말씀',
  '하다',
  '주',
  '시기',
  '바라다'],
 ['지',
  '원자',
  '님',
  '개인',
  '적',
  '공부',
  '어떻다',
  '하다',
  '강의',
  '나',
  '책',
  '활용',
  '공부',
  '법',
  '말씀',
  '하다',
  '주다',
  '좋다'],
 ['저희',
  '회사',
  '더',
  '갖추다',
  '나가야',
  '하다',
  '덕목',
  '무엇',
  '이라고',
  '생각',
  '하다',
  '지',
  '원자',
  '님',
  '께서',
  '생각',
  '하다',
  '좋다',
  '회사',
  '대해',
  '서도',
  '함께',
  '말씀',
  '하다',
  '줄다'],
 ['지',
  '원자',
  '님',
  '성격',
  '상',
  '장점',
  '단점',
  '대해',
  '각각',
  '말씀',
  '하다',
  '줄다',
  '장점',
  '단점',
  '구체',
  '적',
  '인',
  '예시',
  '들다',
  '주다',
  '좋다',
  '말씀',
  '하다',
  '줄다'],
 ['음',
  '평소',
  '개인',
  '작업',
  '하다',
  '편',
  '인가요',
  '만약',
  '그렇다',
  '그렇게',
  '하다',
  '있다',
  '원동력',
  '무엇',
  '이라고',
  '생각',
  '하다',
  '말씀',
  '부탁',
  '드리다'],
 ['지',
  '원자',
  '님',
  '께서',
  '지금',
  '협업',
  '하다',
  '가장',
  '어렵다',
  '것',
  '어려움',
  '어떻다',
  '해결',
  '하다',
  '함께',
  '말씀',
  '하다',
  '줄다'],
 ['하다',
  '보다',
  '본인',
  '열심히',
  '하지만',
  '원하다',
  '만큼',
  '따라오다',
  '못',
  '하다',
  '팀',
  '동료',
  '들',
  '있다',
  '있다',
  '본인',
  '이렇다',
  '때',
  '어떻다',
  '하나요'],
 ['살다',
  '다양하다',
  '커뮤니케이션',
  '경험',
  '해',
  '보다',
  '중',
  '에서',
  '제일',
  '어렵다',
  '경험',
  '하다',
  '만',
  '골',
  '라서',
  '설명',
  '하다',
  '주',
  '시기',
  '바라다'],
 ['기차',
  '운행',
  '시',
  '산사태',
  '로',
  '삼십',
  '분',
  '정차',
  '되어다',
  '가정',
  '해',
  '보다',
  '때',
  '관리',
  '책임',
  '위치',
  '있다',
  '어떻다',
  '조치',
  '하다',
  '건지다',
  '말씀',
  '해',
  '주',
  '시기',
  '바라다'],
 ['지',
  '원자',
  '님',
  '께서',
  '하다',
  '보다',
  '다른',
  '지역',
  '업무',
  '수여',
  '하다',
  '되다',
  '있다',
  '지',
  '원자',
  '님',
  '타',
  '지역',
  '근무',
  '문제',
  '없이',
  '가능하다'],
 ['지',
  '원자',
  '님',
  '께서는',
  '본인',
  '스스로',
  '숫자',
  '창의',
  '중',
  '에서',
  '어떻다',
  '것',
  '더',
  '가깝다',
  '생각',
  '하다',
  '가깝다',
  '것',
  '대한',
  '이유',
  '같이',
  '말씀',
  '하다',
  '줄다'],
 ['특별하다',
  '가다',
  '회사',
  '있다',
  '있다',
  '어떻다',
  '것',
  '중요하다',
  '특정',
  '도메인',
  '이나',
  '회사',
  '분위기',
  '그렇다',
  '것',
  '들',
  '중',
  '어떻다',
  '점',
  '중점',
  '적',
  '보다',
  '궁금하다'],
 ['지원',
  '자',
  '께서는',
  '우리',
  '회사',
  '디자인',
  '부문',
  '지원',
  '하다',
  '그렇다',
  '본인',
  '하다',
  '디자인',
  '있다',
  '신지',
  '그것',
  '대해',
  '말씀',
  '하다',
  '보다'],
 ['지',
  '원자',
  '님',
  '협업',
  '하다',
  '때',
  '가장',
  '중요하다',
  '생각',
  '하다',
  '것',
  '어떻다',
  '것',
  '이다',
  '왜',
  '그걸',
  '중요하다',
  '생각',
  '하다',
  '한번',
  '말씀',
  '하다',
  '줄다'],
 ['본인',
  '전공',
  '것',
  '외',
  '수준',
  '급',
  '실력',
  '노력',
  '것',
  '있다',
  '그게',
  '무엇',
  '인지',
  '궁금하다',
  '분야',
  '전공',
  '하다',
  '어떻다',
  '도움',
  '주다',
  '궁금하다'],
 ['커뮤니케이션',
  '자다',
  '하다',
  '있다',
  '본인',
  '스킬',
  '있다',
  '하다',
  '번',
  '소개',
  '하다',
  '주다',
  '직접',
  '하다',
  '번',
  '보여주다',
  '좋다'],
 ['현재',
  '읽다',
  '계시다',
  '책',
  '있다',
  '가요',
  '있다',
  '무슨',
  '책',
  '인지',
  '궁금하다',
  '왜',
  '책',
  '읽다',
  '이유',
  '함께',
  '말씀',
  '하다',
  '주',
  '시오'],
 ['디자이너', '하다', '가장', '힘들다', '경험', '대해', '말씀', '하다', '주다'],
 ['지',
  '원자',
  '님',
  '께서',
  '그동안',
  '진행',
  '프로젝트',
  '들',
  '가운데',
  '가장',
  '기억',
  '남다',
  '프로젝트',
  '있다',
  '어떻다',
  '프로젝트',
  '그것',
  '어떻다',
  '점',
  '에서',
  '기억',
  '남다',
  '설명',
  '부탁드리다'],
 ['회사',
  '입사',
  '하다',
  '업무',
  '내용',
  '이나',
  '강도',
  '예상',
  '하다',
  '것',
  '과는',
  '전혀',
  '다르다',
  '느껴지다',
  '때',
  '어떻다',
  '하다',
  '건가'],
 ['지원',
  '자',
  '디자인',
  '하다',
  '때',
  '가장',
  '중요하다',
  '생각',
  '하다',
  '무엇',
  '입',
  '니까',
  '그것',
  '자세하다',
  '말씀',
  '하다',
  '줄다'],
 ['현대인',
  '평균',
  '적',
  '하루',
  '세',
  '번의',
  '거짓말',
  '하다',
  '산다',
  '하다',
  '지',
  '원자',
  '님',
  '께서는',
  '내',
  '해보다',
  '거짓말',
  '중',
  '에서',
  '어떻다',
  '거짓말',
  '가장',
  '인상',
  '깊다',
  '남아',
  '있다'],
 ['지',
  '원자',
  '님',
  '께서',
  '분야',
  '지원',
  '하다',
  '어떠하다',
  '노력',
  '해',
  '오다',
  '생각나다',
  '대로',
  '모두',
  '말씀',
  '하다',
  '주',
  '시기',
  '바라다'],
 ['디자이너', '하다', '가장', '힘들다', '경험', '대해', '말씀', '하다', '주다', '어떻다', '것', '있다'],
 ['나',
  '스트레스',
  '해소',
  '방법',
  '있다',
  '있다',
  '왜',
  '그렇다',
  '방법',
  '스트레스',
  '로',
  '해소',
  '하다',
  '말씀',
  '부탁드리다'],
 ['커뮤니케이션',
  '자다',
  '하다',
  '있다',
  '본인',
  '노하우',
  '있다',
  '가요',
  '있다',
  '하다',
  '번',
  '직접',
  '보여주다',
  '소개',
  '해',
  '주다',
  '바라다'],
 ['지',
  '원자',
  '님',
  '본인',
  '장점',
  '단점',
  '설명',
  '하다',
  '줄다',
  '그것',
  '특',
  '화',
  '시키다',
  '극복',
  '하다',
  '위',
  '노력',
  '함께',
  '말씀',
  '하다',
  '줄다'],
 ['지',
  '원자',
  '분',
  '께서',
  '입사',
  '하다',
  '난',
  '뒤',
  '쉽다',
  '어렵다',
  '일이',
  '있다',
  '생각',
  '하다',
  '보다',
  '같다',
  '들',
  '대한',
  '분배',
  '어떻다',
  '하다',
  '생각',
  '신지',
  '어떻다',
  '방식',
  '나누다',
  '처리',
  '하다',
  '궁금하다'],
 ['지',
  '원자',
  '분',
  '께서는',
  '협업',
  '진행',
  '하다',
  '가장',
  '어렵다',
  '점',
  '있다',
  '하다',
  '무엇',
  '이다',
  '그렇게',
  '협업',
  '하다',
  '어렵다',
  '상황',
  '에서도',
  '그렇다',
  '들',
  '어떻다',
  '극복',
  '하다',
  '이야기',
  '하다',
  '줄다'],
 ['최근', '디자인', '트렌드', '무엇', '이라', '생각', '하다'],
 ['지',
  '원자',
  '분',
  '께서',
  '대학',
  '에서',
  '배우다',
  '전공',
  '과목',
  '들',
  '중',
  '에서',
  '가장',
  '기억',
  '남다',
  '과목',
  '대해',
  '이야기',
  '하다',
  '주시',
  '면',
  '좋다',
  '중',
  '에서',
  '하다',
  '만',
  '골',
  '라서',
  '인상',
  '깊다',
  '내용',
  '설명',
  '하다',
  '줄다'],
 ['회사',
  '들어오다',
  '되다',
  '기존',
  '과는',
  '다른',
  '업무',
  '스타일',
  '수도',
  '있다',
  '혹시',
  '기존',
  '다른',
  '업무',
  '스타일',
  '에는',
  '자다',
  '적응하다',
  '편',
  '이신',
  '가요'],
 ['지',
  '원자',
  '님',
  '회사',
  '들어오다',
  '선배',
  '만나다',
  '되다',
  '어떻다',
  '모습',
  '선배',
  '만나다',
  '그렇게',
  '생각',
  '하다',
  '이유',
  '함께',
  '설명',
  '부탁드리다'],
 ['지',
  '원자',
  '님',
  '께서',
  '최근',
  '보다',
  '뉴스',
  '나',
  '접',
  '뉴스',
  '들',
  '가운데',
  '가장',
  '인상',
  '깊다',
  '뉴스',
  '무엇',
  '입',
  '니까',
  '왜',
  '뉴스',
  '인상',
  '깊다',
  '이유',
  '함께',
  '말씀',
  '하다',
  '주',
  '시기',
  '바라다'],
 ['사적',
  '인',
  '질문',
  '이라고',
  '생각',
  '하다',
  '수도',
  '있다',
  '주변',
  '친구',
  '들',
  '중',
  '하다',
  '명',
  '고르다',
  '칭찬',
  '해',
  '줄다',
  '칭찬',
  '구체',
  '적',
  '이고',
  '자세하다',
  '칭찬',
  '일수록',
  '좋다',
  '답변',
  '이라고',
  '생각',
  '하다',
  '있다'],
 ['귀하다',
  '디자인',
  '담당자',
  '유',
  '엑스',
  '디자인',
  '무엇',
  '이라고',
  '생각',
  '하다',
  '본인',
  '생각',
  '말씀',
  '하다',
  '줄다'],
 ['지금',
  '살아오다',
  '새롭다',
  '환경',
  '에서',
  '전혀',
  '모르다',
  '맡다',
  '해보다',
  '경험',
  '혹시',
  '있다',
  '가요',
  '있다',
  '경험',
  '대해',
  '하다',
  '번',
  '말씀',
  '하다',
  '주',
  '시기',
  '바라다'],
 ['열심히',
  '늘다',
  '하지만',
  '본인',
  '원하다',
  '만큼',
  '따라오다',
  '못',
  '하다',
  '팀',
  '동료',
  '들',
  '있다',
  '있다',
  '그렇다',
  '동료',
  '들',
  '에게',
  '지',
  '원자',
  '님',
  '께서는',
  '어떻다',
  '하다',
  '본인',
  '생각',
  '말',
  '하다',
  '번',
  '말씀',
  '하다',
  '보다'],
 ['혹시',
  '역사',
  '속',
  '가장',
  '존경',
  '하다',
  '인물',
  '있다',
  '인물',
  '가장',
  '존경',
  '하다',
  '이유',
  '대해',
  '말씀',
  '하다',
  '줄다',
  '있다'],
 ['저희', '특성', '상', '야근', '이나', '잔업', '외근', '많아지다', '있다', '그래도', '괜찮다'],
 ['지',
  '원자',
  '님',
  '께서',
  '본인',
  '현재',
  '있다',
  '위치',
  '보다',
  '어렵다',
  '목표',
  '달성',
  '적',
  '있다',
  '경험',
  '말씀',
  '하다',
  '주',
  '시오'],
 ['전공',
  '외',
  '자신',
  '수준',
  '급',
  '실력',
  '되다',
  '정도',
  '로',
  '노력',
  '것',
  '있다',
  '만약',
  '있다',
  '전공',
  '하다',
  '어떻다',
  '도움',
  '주다',
  '궁금하다'],
 ['직무',
  '수행',
  '중',
  '난관',
  '봉착',
  '하다',
  '어떠하다',
  '방식',
  '해결',
  '하다',
  '지',
  '원자',
  '님',
  '해결',
  '법',
  '이유',
  '말씀',
  '하다',
  '주',
  '시기',
  '바라다'],
 ['면접',
  '자',
  '님',
  '께서',
  '그동안',
  '인생',
  '에서',
  '겪다',
  '갈등',
  '들',
  '중',
  '에서',
  '가장',
  '심각하다',
  '갈등',
  '무엇',
  '이다',
  '그중',
  '하다',
  '만',
  '골',
  '라서',
  '설명',
  '부탁드리다'],
 ['면접',
  '자',
  '께서',
  '따로',
  '진행',
  '하다',
  '프로젝트',
  '있다',
  '가요',
  '있다',
  '어떻다',
  '것',
  '이다',
  '설명',
  '부탁드리다'],
 ['면접',
  '자',
  '께서',
  '읽다',
  '책',
  '중',
  '가장',
  '감명',
  '깊다',
  '읽다',
  '책',
  '혹은',
  '감명',
  '깊다',
  '보다',
  '영화',
  '무엇',
  '인지',
  '설명',
  '부탁드리다'],
 ['본인',
  '경험',
  '비추다',
  '보다',
  '때',
  '본인',
  '어떻다',
  '문제',
  '부딪치다',
  '때',
  '혼자',
  '해결',
  '하다',
  '편',
  '이신',
  '가요',
  '아니다',
  '여러',
  '사람',
  '들',
  '에게',
  '이야기',
  '하다',
  '편',
  '이신',
  '가요',
  '어떻다',
  '방식',
  '문제',
  '해결',
  '하다',
  '궁금하다'],
 ['남',
  '들',
  '과는',
  '다른',
  '자신',
  '경쟁력',
  '있다',
  '말씀',
  '하다',
  '줄다',
  '경쟁력',
  '키우다',
  '어떻다',
  '노력',
  '하다'],
 ['업무',
  '중',
  '스케줄',
  '없다',
  '일이',
  '생기다',
  '때',
  '많다',
  '이렇다',
  '상황',
  '생기다',
  '지',
  '원자',
  '님',
  '께선',
  '어떻다',
  '대처',
  '하다'],
 ['시험',
  '기간',
  '같이',
  '시간',
  '촉박하다',
  '때',
  '어떻다',
  '시간',
  '관리',
  '하다',
  '지',
  '원자',
  '님',
  '시간',
  '관리',
  '법',
  '소개',
  '하다',
  '주다',
  '바라다'],
 ['만약',
  '지',
  '원자',
  '님',
  '께서',
  '상사',
  '회사',
  '이익',
  '반하다',
  '행동',
  '하다',
  '것',
  '직접',
  '목격',
  '하다',
  '그때',
  '어떻다',
  '대처',
  '하다'],
 ['열심히',
  '하다',
  '본인',
  '원하다',
  '만큼',
  '따라오다',
  '못',
  '하다',
  '팀',
  '동료',
  '들',
  '가끔',
  '있다',
  '이렇다',
  '때',
  '지',
  '원자',
  '님',
  '동료',
  '어떻다',
  '하다'],
 ['하다', '되다', '중국', '출장', '갈다', '일이', '생기다', '있다', '중국', '출장', '괜찮다', '가요'],
 ['글로벌',
  '인재',
  '에게',
  '필수',
  '요소',
  '무엇',
  '이라고',
  '생각',
  '하다',
  '지',
  '원자',
  '님',
  '능력',
  '노력',
  '하다',
  '오신',
  '것',
  '무엇',
  '이다'],
 ['지',
  '원자',
  '님',
  '께서',
  '진행',
  '하다',
  '어떻다',
  '부분',
  '어리다',
  '것',
  '이라고',
  '예측',
  '있다',
  '나중',
  '문제',
  '마주',
  '하다',
  '되다',
  '어떻다',
  '해결',
  '하다',
  '말씀',
  '하다',
  '줄다'],
 ['지',
  '원자',
  '님',
  '께서',
  '업무',
  '시',
  '분쟁',
  '발생',
  '하다',
  '때',
  '대비',
  '지',
  '원자',
  '님',
  '만에',
  '대처',
  '법',
  '있다',
  '지',
  '원자',
  '님',
  '있다',
  '무엇',
  '인지',
  '설명',
  '함께',
  '이야기',
  '하다',
  '줄다'],
 ['본인',
  '개인',
  '적',
  '공부',
  '어떻다',
  '하다',
  '궁금하다',
  '강의',
  '혹은',
  '책',
  '활용',
  '공부',
  '방법',
  '말씀',
  '하다',
  '주다',
  '좋다'],
 ['지',
  '원자',
  '님',
  '께서는',
  '자신',
  '스트레스',
  '해소',
  '법',
  '있다',
  '가요',
  '있다',
  '왜',
  '그러하다',
  '방법',
  '스트레스',
  '해소',
  '하다',
  '대해',
  '설명',
  '부탁드리다'],
 ['만약',
  '상사',
  '업무',
  '무관',
  '시키다',
  '자다',
  '수행',
  '하다',
  '자신',
  '있다',
  '가요',
  '아니다',
  '솔직하다',
  '수행',
  '하다',
  '않다',
  '건지다',
  '말씀',
  '하다',
  '줄다'],
 ['인력',
  '이나',
  '시간',
  '등',
  '자원',
  '부족하다',
  '상황',
  '업무',
  '끝',
  '수행',
  '하다',
  '경험',
  '있다',
  '말씀',
  '하다',
  '줄다',
  '최대한',
  '구체',
  '적',
  '말씀',
  '하다',
  '주다',
  '바라다'],
 ['지',
  '원자',
  '님',
  '께서',
  '현대',
  '사회',
  '에서',
  '없다',
  '되다',
  '가장',
  '중요하다',
  '생각',
  '하다',
  '직업',
  '하다',
  '만',
  '고르다',
  '말씀',
  '부탁드리다',
  '간단하다',
  '설명',
  '해',
  '줄다'],
 ['저희', '특성', '상', '야근', '이나', '잔업', '외근', '많아지다', '있다', '그래도', '괜찮다'],
 ['지',
  '원자',
  '님',
  '께서',
  '그동안',
  '속',
  '해',
  '있다',
  '조직',
  '이나',
  '단체',
  '에서',
  '어떻다',
  '역할',
  '맡다',
  '사람',
  '이다',
  '궁금하다',
  '본인',
  '어떻다',
  '사람',
  '이다',
  '대해',
  '말씀',
  '하다',
  '줄다'],
 ['면접',
  '자',
  '님',
  '평소',
  '검색',
  '자주',
  '하다',
  '그렇다',
  '어떻다',
  '검색',
  '하다',
  '왜',
  '검색',
  '하다',
  '궁금하다'],
 ['지',
  '원자',
  '님',
  '께서는',
  '이전',
  '직장',
  '에서',
  '퇴사',
  '것',
  '후회',
  '하다',
  '적다',
  '없다',
  '가요',
  '만약',
  '후회',
  '하다',
  '적',
  '있다',
  '왜',
  '후회',
  '적',
  '있다',
  '신지',
  '이유',
  '함께',
  '말씀',
  '하다',
  '주다',
  '좋다',
  '것',
  '같다'],
 ['지',
  '원자',
  '님',
  '태어나다',
  '지금',
  '하다',
  '가운데',
  '가장',
  '후회되다',
  '일이',
  '어떻다',
  '이다',
  '궁금하다',
  '하다',
  '만',
  '골',
  '라서',
  '이야기',
  '하다',
  '주다'],
 ['좋아하다', '디자인', '브랜드', '이유', '무엇', '인지', '이야기', '하다', '줄다'],
 ['존경',
  '하다',
  '디자이너',
  '제품',
  '대해',
  '설명',
  '하다',
  '보다',
  '패션',
  '브랜드',
  '밖에',
  '카테고리',
  '상관',
  '없다'],
 ['만약',
  '상사',
  '업무',
  '무관',
  '시키다',
  '자다',
  '수행',
  '하다',
  '자신',
  '있다',
  '아니다',
  '솔직하다',
  '수행',
  '하다',
  '않다',
  '것',
  '인지',
  '말씀',
  '하다',
  '줄다'],
 ['평소',
  '검색',
  '자주',
  '하다',
  '편',
  '인가요',
  '어떻다',
  '검색',
  '하다',
  '왜',
  '그것',
  '검색',
  '하다',
  '이유',
  '함께',
  '말씀',
  '하다',
  '주다',
  '좋다'],
 ['지',
  '원자',
  '분',
  '디자이너',
  '있다',
  '으로의',
  '목표',
  '있다',
  '목표',
  '있다',
  '그것',
  '관해',
  '설명',
  '부탁드리다'],
 ['하다',
  '보다',
  '상사',
  '트러블',
  '생기다',
  '있다',
  '이러하다',
  '상황',
  '에서',
  '어떻다',
  '대처',
  '하다',
  '겁',
  '니까',
  '상사',
  '혼내다',
  '기분',
  '나쁘다',
  '않다'],
 ['현대',
  '사회',
  '많다',
  '직업',
  '들',
  '있다',
  '중',
  '에서',
  '없다',
  '되다',
  '가장',
  '중요하다',
  '생각',
  '하다',
  '직업',
  '하다',
  '만',
  '골',
  '라서',
  '한번',
  '말씀',
  '하다',
  '주다'],
 ['오늘',
  '시점',
  '부터',
  '뒤',
  '내',
  '주요',
  '성장',
  '계획',
  '이나',
  '목표',
  '혹시',
  '있다',
  '있다',
  '혹시',
  '무엇',
  '일지',
  '저희',
  '한테',
  '소개',
  '하다',
  '번만',
  '부탁드리다'],
 ['나',
  '스트레스',
  '해소',
  '법',
  '있다',
  '가요',
  '있다',
  '왜',
  '그렇다',
  '방법',
  '스트레스',
  '하다',
  '되다',
  '이유',
  '말씀',
  '하다',
  '줄다',
  '있다',
  '가요'],
 ['좋다', '디자인', '이란', '무엇', '이라고', '생각', '하다', '설명', '하다', '주다'],
 ['남',
  '자다',
  '따르다',
  '팔로우',
  '형',
  '남',
  '자다',
  '이끌다',
  '리더',
  '형',
  '지',
  '원자',
  '님',
  '께서는',
  '어떻다',
  '유형',
  '이라고',
  '생각',
  '하다',
  '이유',
  '함께',
  '말씀',
  '하다',
  '줄다'],
 ['지',
  '원자',
  '님',
  '께서는',
  '분야',
  '지원',
  '하다',
  '되다',
  '어떻다',
  '노력',
  '하다',
  '하다',
  '생각나다',
  '대로',
  '말씀',
  '해',
  '주시',
  '면',
  '되다'],
 ['다른',
  '많다',
  '지원',
  '자',
  '분',
  '들',
  '있다',
  '같다',
  '많다',
  '지원',
  '자',
  '분들',
  '가운데',
  '지금',
  '지원',
  '자',
  '분',
  '께서',
  '계시다',
  '차별성',
  '장점',
  '어필',
  '하다',
  '있다',
  '하다',
  '뭐라다',
  '이야기',
  '하다',
  '궁금하다'],
 ['글로벌',
  '인재',
  '에게',
  '필수',
  '요소',
  '무엇',
  '이다',
  '지원',
  '자',
  '그것',
  '노력',
  '하다',
  '온',
  '것',
  '무엇',
  '인지',
  '말씀',
  '부탁드리다'],
 ['요즘',
  '고령화',
  '사회',
  '로',
  '가면',
  '치매',
  '로',
  '인하다',
  '문제',
  '나타나다',
  '있다',
  '지',
  '원자',
  '님',
  '께서는',
  '대해',
  '건보',
  '공단',
  '어떻다',
  '하다',
  '하다',
  '개선',
  '하다',
  '방안',
  '무엇',
  '있다',
  '한번',
  '말씀',
  '하다',
  '줄다',
  '있다'],
 ['입사',
  '후',
  '근무',
  '하다',
  '정작',
  '지원',
  '분야',
  '본인',
  '자다',
  '맞다',
  '않다',
  '사실',
  '깨닫다',
  '되다',
  '본인',
  '어떻다',
  '하다',
  '생각',
  '인가요'],
 ['본인',
  '장점',
  '단점',
  '대해',
  '설명',
  '하다',
  '주시',
  '그것',
  '특',
  '화',
  '시키다',
  '극복',
  '하다',
  '그동안',
  '기울이다',
  '오다',
  '노력',
  '대해',
  '서도',
  '함께',
  '말씀',
  '하다',
  '주다',
  '바라다'],
 ['오늘',
  '면접',
  '다양하다',
  '준비',
  '노력',
  '하다',
  '지',
  '원자',
  '님',
  '께서는',
  '어떻다',
  '방식',
  '면접',
  '준비',
  '하다',
  '말씀',
  '한번',
  '부탁드리다'],
 ['협업',
  '하다',
  '때',
  '가장',
  '중요시',
  '여기다',
  '부분',
  '있다',
  '있다',
  '무엇',
  '인지',
  '이유',
  '말씀',
  '하다',
  '줄다'],
 ['본인',
  '지금',
  '살다',
  '이루다',
  '성과',
  '중',
  '가장',
  '크다',
  '성과',
  '무엇',
  '인가요',
  '본인',
  '생각',
  '하다',
  '자랑',
  '하다',
  '있다',
  '만큼',
  '크다',
  '성과',
  '말씀',
  '하다',
  '주다',
  '바라다'],
 ['이전',
  '직장',
  '그만두다',
  '특별하다',
  '이유',
  '있다',
  '혹시',
  '어떻다',
  '이유',
  '에서',
  '그만두다',
  '지금',
  '직장',
  '같다',
  '이유',
  '로',
  '그만두다',
  '가능성',
  '있다',
  '궁금하다'],
 ['지금',
  '살',
  '아',
  '오다',
  '가장',
  '힘들다',
  '경험',
  '무엇',
  '인가요',
  '힘들다',
  '상황',
  '어떻다',
  '극복',
  '하다',
  '말씀',
  '하다',
  '줄다'],
 ['지',
  '원자',
  '님',
  '여태',
  '살아오다',
  '다양하다',
  '커뮤니케이션',
  '경험',
  '하다',
  '보다',
  '중',
  '에서',
  '가장',
  '어렵다',
  '커뮤니케이션',
  '하다',
  '만',
  '꼽자',
  '면',
  '경험',
  '자세하다',
  '설명',
  '하다',
  '줄다'],
 ['만약',
  '이직',
  '생각',
  '하다',
  '동료',
  '만나다',
  '되다',
  '뭐라다',
  '말씀',
  '하다',
  '건가',
  '왜',
  '그렇게',
  '하다',
  '건지다',
  '설명',
  '부탁드리다'],
 ['업무',
  '수행',
  '하다',
  '보다',
  '분쟁',
  '발생',
  '하다',
  '있다',
  '분쟁',
  '발생',
  '하다',
  '때',
  '지',
  '원자',
  '님',
  '대처',
  '법',
  '있다',
  '말씀',
  '하다',
  '줄다'],
 ['협업',
  '하다',
  '때',
  '가장',
  '중요하다',
  '생각',
  '하다',
  '것',
  '무엇',
  '인지',
  '왜',
  '그것',
  '가장',
  '중요하다',
  '생각',
  '하다',
  '말씀',
  '부탁드리다'],
 ['지',
  '원자',
  '님',
  '께서',
  '살다',
  '가장',
  '힘들다',
  '점',
  '무엇',
  '입',
  '니까',
  '지',
  '원자',
  '님',
  '점',
  '극복',
  '하다',
  '어떠하다',
  '노력',
  '하다',
  '설명',
  '함께',
  '궁금하다'],
 ['본인',
  '작업',
  '디자인',
  '우수',
  '성',
  '알리다',
  '발표',
  '하다',
  '보다',
  '경험',
  '있다',
  '가요',
  '있다',
  '경험',
  '대해',
  '말씀',
  '하다',
  '줄다'],
 ['남',
  '자다',
  '이끌다',
  '리더',
  '형',
  '남',
  '자다',
  '따르다',
  '팔로워',
  '형',
  '본인',
  '어떻다',
  '유형',
  '인지',
  '말씀',
  '하다',
  '주시',
  '이유',
  '함께',
  '설명',
  '하다',
  '줄다'],
 ['지',
  '원자',
  '님',
  '께서는',
  '최근',
  '재미있다',
  '하다',
  '계시다',
  '일이',
  '있다',
  '그렇다',
  '일이',
  '왜',
  '재미있다',
  '대해',
  '서도',
  '설명',
  '부탁드리다'],
 ['의사소통',
  '자다',
  '하다',
  '있다',
  '나',
  '스킬',
  '있다',
  '말씀',
  '해',
  '주시',
  '지금',
  '한번',
  '보여주다',
  '좋다'],
 ['만약',
  '지',
  '원자',
  '님',
  '께서',
  '께',
  '임',
  '속',
  '캐릭터',
  '되다',
  '지',
  '원자',
  '님',
  '어떻다',
  '께',
  '임',
  '속',
  '에서',
  '어떻다',
  '역할',
  '맡다',
  '수행',
  '하다',
  '신지',
  '말씀',
  '하다',
  '줄다'],
 ['요즘',
  '고령화',
  '사회',
  '로',
  '가면',
  '치매',
  '로',
  '인하다',
  '문제',
  '대두',
  '되다',
  '있다',
  '대해',
  '건보',
  '공단',
  '하다',
  '일과',
  '개선',
  '하다',
  '방안',
  '대해',
  '말씀',
  '하다',
  '주다'],
 ['지',
  '원자',
  '님',
  '께서',
  '창의',
  '적',
  '어떻다',
  '문제',
  '직접',
  '해결',
  '하다',
  '보다',
  '경험',
  '있다',
  '있다',
  '그것',
  '어떻다',
  '경험',
  '이다',
  '과정',
  '최대한',
  '자세하다',
  '설명',
  '하다',
  '주시',
  '면',
  '좋다'],
 ['좋아하다',
  '브랜드',
  '있다',
  '있다',
  '왜',
  '브랜드',
  '좋아하다',
  '말씀',
  '하다',
  '주시',
  '브랜드',
  '란',
  '무엇',
  '이라고',
  '생각',
  '하다',
  '설명',
  '해',
  '주',
  '시오'],
 ['주변',
  '친구',
  '들',
  '중',
  '하다',
  '명',
  '골',
  '라서',
  '칭찬',
  '해',
  '줄다',
  '가능하다',
  '구체',
  '적',
  '이고',
  '자세하다',
  '칭찬',
  '하다',
  '주시',
  '면',
  '더욱',
  '좋다',
  '것',
  '같다'],
 ['지',
  '원자',
  '님',
  '께서',
  '역사',
  '속',
  '에서',
  '가장',
  '존경',
  '하다',
  '인물',
  '말씀',
  '하다',
  '주다',
  '바라다',
  '해당',
  '인물',
  '가장',
  '존경',
  '하다',
  '이유',
  '대해',
  '서도',
  '말씀',
  '하다',
  '줄다'],
 ['지금',
  '인생',
  '살다',
  '가장',
  '후회되다',
  '일이',
  '무엇',
  '이다',
  '하다',
  '만',
  '말씀',
  '하다',
  '줄다',
  '있다'],
 ['전공',
  '외',
  '자신',
  '수준',
  '급',
  '실력',
  '되다',
  '정도',
  '로',
  '노력',
  '것',
  '있다',
  '전공',
  '하다',
  '어떠하다',
  '도움',
  '줄',
  '있다'],
 ['면접', '자', '님', '디자인', '하다', '때', '가장', '중요시', '여기다', '무엇', '인가요'],
 ['지',
  '원자',
  '님',
  '성격',
  '상',
  '장점',
  '단점',
  '대해',
  '각각',
  '말씀',
  '하다',
  '줄다',
  '구체',
  '적',
  '인',
  '예시',
  '들다',

In [39]:
# 모델 학습 (qna 합쳐서 할지 분리해서 할지 고민)
from gensim.models import Word2Vec

model = Word2Vec(
    sentences=preprocessed_q_data,
    vector_size=100,
    window=5,
    min_count=5,
    sg=1
)

In [40]:
model.wv.vectors.shape

(2066, 100)

In [41]:
pd.DataFrame(model.wv.vectors, index=model.wv.index_to_key).head(5)

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
하다,-0.137229,-0.009997,0.342003,-0.117119,-0.021398,-0.312029,0.058187,0.507729,-0.277654,-0.099654,...,-0.033547,-0.115812,-0.114991,-0.113006,0.598972,0.197700,0.205091,0.026118,0.248032,-0.145421
있다,-0.213116,0.259798,0.268706,0.351467,0.097641,0.194099,-0.203379,0.413224,-0.108816,0.036332,...,0.124037,-0.313121,0.044861,0.217261,0.097315,0.208491,0.123738,-0.176696,-0.015432,0.187012
어떻다,0.038922,0.032262,-0.217306,0.095040,0.097421,-0.301920,-0.082884,0.466303,-0.220048,-0.115996,...,0.224986,-0.085783,-0.005810,-0.288091,0.299272,0.155474,0.181396,-0.084059,0.355295,-0.120077
말씀,0.087033,0.061536,0.315356,-0.099269,-0.006580,-0.168355,-0.239484,0.529474,-0.265843,-0.056771,...,0.009051,0.338323,0.366235,0.336204,0.395854,0.109132,0.415545,0.046822,-0.134533,0.283213
지,-0.535920,0.288651,0.280080,0.009207,-0.054651,0.082730,0.051954,0.116324,0.001063,0.086812,...,0.147160,-0.488693,-0.197741,-0.298025,0.110423,-0.149035,0.420328,0.019370,0.191073,0.123678

In [42]:
# 유사도 계산

model.wv.most_similar('업무')

[('이동', 0.5978502631187439),
 ('적응', 0.5560382008552551),
 ('관계', 0.5461598634719849),
 ('와는', 0.5427963733673096),
 ('상관', 0.5293045043945312),
 ('막상', 0.5165571570396423),
 ('스타', 0.513508677482605),
 ('이처럼', 0.5124068856239319),
 ('원래', 0.5100269317626953),
 ('나중', 0.5041428208351135)]

In [43]:
# 모델 저장

model.wv.save_word2vec_format('interview')